// Code generated by mockery v2.42.1. DO NOT EDIT.

package mockerys

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BeefAPICaller is an autogenerated mock type for the BeefAPICaller type
type BeefAPICaller struct {
	mock.Mock
}

type BeefAPICaller_Expecter struct {
	mock *mock.Mock
}

func (_m *BeefAPICaller) EXPECT() *BeefAPICaller_Expecter {
	return &BeefAPICaller_Expecter{mock: &_m.Mock}
}

// FetchBeefData provides a mock function with given fields: ctx
func (_m *BeefAPICaller) FetchBeefData(ctx context.Context) (*string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchBeefData")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BeefAPICaller_FetchBeefData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchBeefData'
type BeefAPICaller_FetchBeefData_Call struct {
	*mock.Call
}

// FetchBeefData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BeefAPICaller_Expecter) FetchBeefData(ctx interface{}) *BeefAPICaller_FetchBeefData_Call {
	return &BeefAPICaller_FetchBeefData_Call{Call: _e.mock.On("FetchBeefData", ctx)}
}

func (_c *BeefAPICaller_FetchBeefData_Call) Run(run func(ctx context.Context)) *BeefAPICaller_FetchBeefData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BeefAPICaller_FetchBeefData_Call) Return(_a0 *string, _a1 error) *BeefAPICaller_FetchBeefData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BeefAPICaller_FetchBeefData_Call) RunAndReturn(run func(context.Context) (*string, error)) *BeefAPICaller_FetchBeefData_Call {
	_c.Call.Return(run)
	return _c
}

// NewBeefAPICaller creates a new instance of BeefAPICaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBeefAPICaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *BeefAPICaller {
	mock := &BeefAPICaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
